workflows:

  # ─── Android Debug APK ──────────────────────────────────────────────────────
  android-build:
    name: Android Build (Debug)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prepare web assets
        script: node prepare.js
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  # ─── iOS App Store Build ────────────────────────────────────────────────────
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 20
      cocoapods: default
      groups:
        - ios_signing   # APP_STORE_CONNECT_KEY_IDENTIFIER, ISSUER_ID, PRIVATE_KEY
      vars:
        BUNDLE_ID: com.blablabla.app
        APP_NAME: BlaBlaBlaLive

    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files from Apple
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set Xcode code signing
        script: xcode-project use-profiles

      - name: Install dependencies
        script: npm install

      - name: Prepare web assets
        script: node prepare.js

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Set build number
        script: |
          # Use git commit count — always unique and incrementing
          BUILD_NUMBER=$(git rev-list HEAD --count)
          echo "Build number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/App/App/Info.plist

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
