workflows:

  # ─── Android Release (Google Play) ──────────────────────────────────────────
  android-release:
    name: Android Release (Google Play)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 20
      groups:
        - android_signing  # CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD, GCLOUD_SERVICE_ACCOUNT_CREDENTIALS

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Prepare web assets
        script: node prepare.js

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/release.keystore

      - name: Build Android AAB (release)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_BUILD_DIR/android/app/release.keystore \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD

    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false

  # ─── iOS App Store Build ────────────────────────────────────────────────────
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 20
      cocoapods: default
      groups:
        - ios_signing   # APP_STORE_CONNECT_KEY_IDENTIFIER, ISSUER_ID, PRIVATE_KEY
      vars:
        BUNDLE_ID: com.blablabla.app
        APP_NAME: BlaBlaBlaLive

    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files from Apple
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set Xcode code signing
        script: xcode-project use-profiles

      - name: Install dependencies
        script: npm install

      - name: Prepare web assets
        script: node prepare.js

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Set build number
        script: |
          # Use git commit count — always unique and incrementing
          BUILD_NUMBER=$(git rev-list HEAD --count)
          echo "Build number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" ios/App/App/Info.plist

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
