workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prepare web assets
        script: node prepare.js
      - name: Sync Capacitor Android
        script: npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-build:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 20
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Prepare web assets
        script: node prepare.js
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS (unsigned)
        script: |
          cd ios/App
          xcodebuild build \
            -workspace App.xcworkspace \
            -scheme App \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app
